### ISSUE TITLE
API - not returning clear amount

### ISSUE THREAD

**Issue by jaku** [triwave/MakersofMario#17]
API does not reply with clears on a level, only clears of known Maker users.

**Comment by aphex** [comment]
fixed @jaku please verify

**Comment by jaku** [comment]
Clears still appear to not be returning. /level/?method=getLevelByID&levelID=A425-0000-011D-6D2E

**Comment by jaku** [comment]
NM. Fixed!
