### ISSUE TITLE
API - Translated name not working

### ISSUE THREAD

**Issue by jaku** [triwave/MakersofMario#24]
It doesn't appear to working anymore.  Levelcode - 44C3-0000-0211-9B9A

**Comment by aphex** [comment]
fixed @jaku please verify

**Comment by jaku** [comment]
Still appears to be broken.

View level: 44C3-0000-0211-9B9A

**Comment by jaku** [comment]
Fixed!
