### ISSUE TITLE
API - Tag Locked

### ISSUE THREAD

**Issue by jaku** [triwave/MakersofMario#27]
Tag locked is not returned for getTags on worlds.

**Comment by aphex** [comment]
Fixed @jaku please verify

**Comment by jaku** [comment]
Still broken. https://api.makersofmario.com/world/?method=getTags&worldID=21

**Comment by jaku** [comment]
Fixed!
